export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const USER_AUTH_REQUEST = 'REQUEST';
export const USER_AUTH_SUCCESS = 'SUCCESS';
export const USER_AUTH_FAILURE = 'FAILURE';